### ISSUE TITLE
Add Object detection head to Encoder-Decoder

### ISSUE THREAD

**Issue by alishan2040** [bcmi/DIRL#3]
Hello,

Thanks for providing the implementation. Your work is very interesting. I'm interested to re-train this network to add object detection head at the end of this network in order to predict (mask, bounding box and class label) in the single network from tampered images. Can you please point where should I begin from? I want to use existing resnet features for detection + classification.

Any advice would be appreciated.
Thanks.

**Comment by jimleungjing** [comment]
Hi,
Thanks for your attention. There is an image manipulation work that starts from the detection backbone:
https://github.com/HuizhouLi/Constrained-R-CNN
And I think this work will inspire you.

**Comment by alishan2040** [comment]
Thanks
