### ISSUE TITLE
Unable to change backbone when training

### ISSUE THREAD

**Issue by alishan2040** [bcmi/DIRL#4]
Hello @jimleungjing,

Thanks for providing the implementation. I'm trying to re-train DIRL network  by changing the backbone from Resnet34 to Resnet50 but it didn't work. Could you please comment on this on how to change the backbone. It seems we have to make some changes in the code in order for it to work?

![image](https://user-images.githubusercontent.com/30209002/156932520-dcc4b312-6e58-4df3-80c7-83f560af80ae.png)

Thanks

**Comment by jimleungjing** [comment]
It seems that the input tensor doesn't match the convolution weight along the channel dimension, and you should check the output channel of each resnet50 layer.
