### ISSUE TITLE
关于图像尺寸的问题

### ISSUE THREAD

**Issue by chchshshhh** [bcmi/DIRL#6]
在运行程序的过程中，我发现评估是采用把图像尺寸规定到224*224来计算评估分数的，请问为什么不将图像还原到原本图像的大小来计算呢？如果说网络的输入输出不是224，而是其他的话，这样的评估是不是可能会产生一定的误差影响？

**Comment by jimleungjing** [comment]
因为训练使用的是224尺寸，训练应与测试的尺寸一致；否则测试使用原始图像大小，模型因为没有见过这样的分辨率会产生预期之外的输出

**Comment by chchshshhh** [comment]
感谢您的解答，但我表达的意思可能有误，我的意思是，在测试的时候模型可以保持224*224输入，而在输出后结果采用双线性插值来得到测试图像的大小来进行评估，就是使用原始的mask来进行评估，这样评估是唯一的，也不用对mask进行resize来匹配预测的处理

**Comment by jimleungjing** [comment]
可以这么做，对所有方法用同一种测评方式就好
