### ISSUE TITLE
Evaluation results for each dataset

### ISSUE THREAD

**Issue by lmdsx** [bcmi/DIRL#7]
May I ask where can I find the results on four sub-datasets in Supplementary in the Inharmonious Region Localization by Magnifying Domain Discrepancy article on AAAI?

**Comment by jimleungjing** [comment]
In fact, we use iHarmony4 dataset: https://github.com/bcmi/Image-Harmonization-Dataset-iHarmony4, which includes the four sub-datasets

**Comment by jimleungjing** [comment]
> May I ask where can I find the results on four sub-datasets in Supplementary in the Inharmonious Region Localization by Magnifying Domain Discrepancy article on AAAI?

In fact, we use iHarmony4 dataset: https://github.com/bcmi/Image-Harmonization-Dataset-iHarmony4, which includes the four sub-datasets

**Comment by jimleungjing** [comment]
> May I ask where can I find the results on four sub-datasets in Supplementary in the Inharmonious Region Localization by Magnifying Domain Discrepancy article on AAAI?

You can run our released model of this repo and [AAAI repo](https://github.com/bcmi/MadisNet-Inharmonious-Region-Localization) on four sub-datasets of  iHarmoney4.

**Comment by ustcnewly** [comment]
> May I ask where can I find the results on four sub-datasets in Supplementary in the Inharmonious Region Localization by Magnifying Domain Discrepancy article on AAAI?

We have uploaded the main paper and supplementary to arXiv https://arxiv.org/pdf/2209.15368.pdf.  We have also released our code and model https://github.com/bcmi/MadisNet-Inharmonious-Region-Localization

**Comment by lmdsx** [comment]
> > May I ask where can I find the results on four sub-datasets in Supplementary in the Inharmonious Region Localization by Magnifying Domain Discrepancy article on AAAI?
> 
> We have uploaded the main paper and supplementary to arXiv https://arxiv.org/pdf/2209.15368.pdf. We have also released our code and model https://github.com/bcmi/MadisNet-Inharmonious-Region-Localization

Thanks!
